import { generateId } from "../../utils/common";

export const data = [
  {
    id: generateId(),
    name: "Excel 1",
    email: "test@test.com",
    phone: "+919769909978",
    sales_machineDetails: [
      {
        id: generateId(),
        sold_to_party: "party 1",
        model: "model 1",
        machine_id: "M001",
        sale_date: new Date(),
        warranty_period: 12,
        current_stamping_date: new Date(),
        stamping_fees: 5000,
        stamping_expenses: 2000,
        future_visit: true,
        monthly_visit: false,
        quarterly_visit: false,
        half_yearly_visit: false,
        yearly_visit: false,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
        specifications:
          "Party 1 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      },
      {
        id: generateId(),
        sold_to_party: "party 2",
        model: "model 2",
        machine_id: "M002",
        sale_date: new Date(),
        warranty_period: 12,
        current_stamping_date: new Date(),
        stamping_fees: 7000,
        stamping_expenses: 4000,
        future_visit: true,
        monthly_visit: false,
        quarterly_visit: false,
        half_yearly_visit: true,
        yearly_visit: false,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
        specifications:
          "Party 2 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      },
    ],
    service_contract_details: [
      {
        id: generateId(),
        sold_to_party: "party 11",
        contract_no: "C001",
        make: "Make One",
        model: "Model 1",
        id_num: "IDN001",
        amc_start_date: new Date(),
        amc_end_date: new Date(),
        monthly_visit: true,
        quarterly_visit: false,
        half_yearly_visit: true,
        yearly_visit: true,
        current_stamping_date: new Date(),
        stamping_fees: 6000,
        stamping_expenses: 3000,
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
      {
        id: generateId(),
        sold_to_party: "party 22",
        contract_no: "C002",
        make: "Make Two",
        model: "Model 2",
        id_num: "IDN002",
        amc_start_date: new Date(),
        amc_end_date: new Date(),
        monthly_visit: true,
        quarterly_visit: false,
        half_yearly_visit: false,
        yearly_visit: true,
        current_stamping_date: new Date(),
        stamping_fees: 8000,
        stamping_expenses: 5000,
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
    ],
    calibration_contract_details: [
      {
        id: generateId(),
        sold_to_party: "party 111",
        contract_no: "C001",
        make: "Make two",
        model: "Model 22",
        id_num: "IDN022",
        calibration_start_date: new Date(),
        calibration_end_date: new Date(),
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        stamping_expenses: 3000,
        current_stamping_date: new Date(),
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
    ],
  },
  {
    id: generateId(),
    name: "Excel 2",
    email: "test2@test.com",
    phone: "+919769909970",
    sales_machineDetails: [
      {
        id: generateId(),
        sold_to_party: "party 1",
        model: "model 1",
        machine_id: "M001",
        sale_date: new Date(),
        warranty_period: 12,
        current_stamping_date: new Date(),
        stamping_fees: 5000,
        stamping_expenses: 2000,
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
        specifications: "specifications one",
      },
    ],
    service_contract_details: [
      {
        id: generateId(),
        sold_to_party: "party 11",
        contract_no: "C001",
        make: "Make One",
        model: "Model 1",
        id_num: "IDN001",
        amc_start_date: new Date(),
        amc_end_date: new Date(),
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        current_stamping_date: new Date(),
        stamping_fees: 6000,
        stamping_expenses: 3000,
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
    ],
    calibration_contract_details: [
      {
        id: generateId(),
        sold_to_party: "party 111",
        contract_no: "C00111",
        make: "Make two",
        model: "Model 22",
        id_num: "IDN0111",
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        stamping_expenses: 3000,
        calibration_start_date: new Date(),
        calibration_end_date: new Date(),
        current_stamping_date: new Date(),
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
      {
        id: generateId(),
        sold_to_party: "party 2222",
        contract_no: "C00222",
        make: "Make two",
        model: "Model 22",
        id_num: "IDN0222",
        calibration_start_date: new Date(),
        calibration_end_date: new Date(),
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        stamping_expenses: 3000,
        current_stamping_date: new Date(),
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
      {
        id: generateId(),
        sold_to_party: "party 3333",
        contract_no: "C00333",
        make: "Make two",
        model: "Model 33",
        id_num: "IDN0333",
        calibration_start_date: new Date(),
        calibration_end_date: new Date(),
        monthly_visit: false,
        quarterly_visit: false,
        half_yearly_visit: false,
        yearly_visit: true,
        stamping_expenses: 3000,
        current_stamping_date: new Date(),
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
    ],
  },
  {
    id: generateId(),
    name: "Customer 3",
    email: "test3@test.com",
    phone: "+919769909971",
    sales_machineDetails: [
      {
        id: generateId(),
        sold_to_party: "party 1",
        model: "model 1",
        machine_id: "M001",
        sale_date: new Date(),
        warranty_period: 12,
        current_stamping_date: new Date(),
        stamping_fees: 5000,
        stamping_expenses: 2000,
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
        specifications: "specifications one",
      },
    ],
    service_contract_details: [
      {
        id: generateId(),
        sold_to_party: "party 11",
        id_num: "IDN001",
        contract_no: "C001",
        make: "Make One",
        model: "Model 1",
        amc_start_date: new Date(),
        amc_end_date: new Date(),
        current_stamping_date: new Date(),
        stamping_fees: 6000,
        stamping_expenses: 3000,
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
    ],
    calibration_contract_details: [
      {
        id: generateId(),
        sold_to_party: "party 111",
        contract_no: "C001",
        make: "Make two",
        model: "Model 22",
        id_num: "IDN022",
        calibration_start_date: new Date(),
        calibration_end_date: new Date(),
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        stamping_expenses: 3000,
        current_stamping_date: new Date(),
        future_visit: true,
        monthly_visit: true,
        quarterly_visit: true,
        half_yearly_visit: true,
        yearly_visit: true,
        edited_on: "",
        edited_by: "",
        created_on: "",
        created_by: "",
      },
    ],
  },
];
